CREATE DATABASE iccolaboradores_db;
USE iccolaboradores_db;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  cpf VARCHAR(20) NOT NULL UNIQUE,
  cidade VARCHAR(100),
  estado VARCHAR(50),
  senha VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome_evento VARCHAR(255) NOT NULL,
  segmento VARCHAR(100),
  descricao TEXT,
  local VARCHAR(255),
  data DATE NOT NULL,
  hora TIME NOT NULL,
  empresa VARCHAR(255),
  organizadores TEXT,
  quantidade_maxima INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE events
ADD COLUMN imagem VARCHAR(255);

SELECT * FROM events;
SELECT * FROM users

